export const sectionData = {
    ['1']: {
        title: "1. Bērnudārzs",
        text: [
            "Ceļa pirmsākumi uz Latvijas universitāti meklējami jau no bērnudārza laikiem, kurā tika apgūtas pirmās prasmes, kuras ir kā pamatas visām zināšanām pirms un arī pēc Latvijas universitātes. Bērnudārza laikā tika nomainīti vairāki bērnudārzi, sāktot ar bērnudārzu Rīgā , pēctam Ķekavā , līdz atkal nonācu atpakaļ tajā pašā Rīgas bērnu dārzā. Bērnudārzu nomaiņas iemesli ir dažādi , bet 2 galvenie ir dzīves vietas maiņa un fakts, ka biju ļoti nepaklausīgs un aktīvs bērns.",
            "Bērnudārza laikā es nebiju tas zēns, kuram patika spēlēties ar mašīnītēm, manu uzmanību pievērsa citas rotaļlietas – inžinierprasmju attīstošas – konstruktori un lego. Pieļauju, ka šis jau bija pirmais indikators, kas norādīja uz manu nokļūšanu Latvijas universitātē, precīzāk, kādā no eksakto zinātņu jomām. Ap 5 gadu vecumu ar tēti sākām risināt pirmās matemātiskās problēmas , ap 6 gadu vecumu sāku jau mācīties reizināšanu un dalīšanu, šīs prasmes man iedeva labu pamatu tālākai virzībai cauri sākumskolai. Bērnudārzu pabeidzu jeb “izlaidos” 2009.gadā, tālāk jau gaidīja skolas durvis."
        ]
    },
    ['2']: {
        title: "2. Pirmā skola (1-6.klase)",
        text: [
            "Sākumskolas gaitas uzsāku Rīgas 6. vidusskolā, skola atrodas pie Ziedoņdārza. Vēl kā tagad atceros kā bija jāgatavojas runai kā pirmās klases skolniekam pirmajā zvanā. Sākumskolu turpināju ar izcilību matemātikā un eksaktajās zinātnēs , pateicoties jau iepriekš apgūtajai matemātikai, taču humantārajās zinātnēs – valodās, man ne tik labi veicās, biežāk bija vēlme tās nemācīties , nekā nesaprašana vai kādas grūtības, šī vēlme nemācīties vēlāk gan sāka jau sakrāties un tad viss biegās (pirms kontroldarbiem) bija ātri jāiemācās, vārdu sakot sarežģīju sev dzīvi.",
            "Sākumskolā arī sāku savu pirmo īsto saskarsni ar datoriem, lai gan iepriekš jau biju tādu izmantojis, sākumskolā sākās patiešām īstā darbošanās ar datoriem, lai gan šo darbošanos uzsāka un turpināja ne tik laba lieta – datorspēles. Datorspēles var teikt ir vadošais iemesls, kas ievilka mani datoru pasaulē. Lejupielādēju pirmo savu spēli, ko man bija parādījis kaimiņu puika – “Counter-Strike”, un būtdams 7 gadus vecs spēlēju datorspēli pilnu ar vardarbību, vēl ar smaidu sejā sauktdams tēti parādīju par jauno aplikāciju uz datora. Prieks gan bija īss, jo tētis nekavējoties lika spēli izdzēst un piekodināja, ja vēlreiz redzēs mani spēlējam “Counter-strike” , tad liegs man pieeju datoram. Tas gan man neliedzas turpināt spēlēt, taču par to vēlāk.",
            "Pa vidu visam sākumskolā vēl bija jāspēlē, kāds mūzikas instruments, izvēlējos spēlēt trompeti , to pašu instrumentu kuru spēlē mans tētis. Godīgi sakot šī bija man visnemīļākā nodarbe. Parasti no mūzikas instrumenta spēlēšanas centos maksimāli izvairīties, nerunājot vēl par trenēšanos mājās – tādas vispār nebija. Papildus tam ar 4. klasi sākumskolā vajadzēja spēlēt orķestrī, orķestri vienmēr notika no plkst. 8:00 līdz 8:40 , ā un es laikam aizmirsu piebilst, ka es esmu tas cilvēks kuram patīk ilgi gulēt, un tad ko es bieži orķestros darīju – gulēju. Varbūt tagad atskatoties , tā nebija labākā attieksme pret orķestra vadītāju, taču toreiz mani interesēja tikai viens – miegs. Tāda arī ir mana muzikanta karjiera īsumā.",
        ]
    },
    ['3']: {
        title: "3. Futbols pa visam pa vidu",
        text: [
            "Var teikt, ka futbols ir bijis man līdzās lielu dzīves daļu, tajā esmu pavadījis vairāk nekā 10 gadus – precīzāk 12 gadus. Futbola gaitas uzsāku 5.gadu vecumā futbola skolā “Metta”, atceros , kā mamma man jautāja vienā dienā, vai vēlos doties uz futbola treniņiem, uz ko atbildēju ar lielu entuziasmu – jā! Ātri vien šie treniņi kļuva par manu ikdienu, lai arī sākumā līdz 10 gadu vecumam šie treniņi bija tikai 3 reizes nedēļā , drīz vien tie kļuva par 5 treniņiem nedēļa un spēlēm brīvdienās.",
            "Ja būtu iespēja izstāstīt par visu piedzīvoto savā futbola karjierā, tad viss sanāktu kā aptuveni 400 lapaspušu grāmata, taču šīs atmiņas vienmēr ir un paliks ar mani. Šis futbola laiks ir pilns ar emocijām gan ar priekiem , gan ar pārdzīvojumiem. Neaizmirstamie mirkļi ar komandas biedriem dažnedažākajos brīžos – uzvarās turnīros , braucieni uz turnīriem gan Latvijā , gan ārzemēs , treniņnometnes vasarās , kā arī kopā pārdzīvotais – pēdējā minūtē zaudēta spēle , neizmantotās iespējas un citi ne tik pozitīvi mirkļi, taču es uzskatu, ka viss piedzīvotais ir veidojis mani kā cilvēku citādāku , nekā ja es nekad nebūtu sācis spēlēt un trenēties futbolā.",
            "Lai arī lielākoties viss sākās ar vēlmi kļūt par futbolistu un spēlēt tādās augsta līmeņa komandās kā “FC Barselona” , “Minhenes Bayern” , “Real Madrid” dzīvē pienāca brīdis, kas visu mainīja.",
        ]
    },
    ['4']: {
        title: "4. Lielīšanās, pārdzīvojums, ģimnāzija",
        text: [
            "Bija pienākusi jau 6.klases vidus un pa šiem skolas gadiem biju jau daudz ko sapratis – mūziķis es noteikti nebūšu , tāpēc sāka rasties vēlme mainīt skolu, kā arī vecāki teica, ka jāsāk lēnām un pamazām domāt par dzīves tālāko gaitu, tā nu arī nolēmu 7. klasē doties uz citu skolu, bet kuru ? Futbolam vēl nebiju atmetis ar roku, un Futbola skola piedāvāja jaunu iespēju – apvienot skolu ar treniņiem, veidojot futbola klasi Rīgas Hanzas vidusskolā, taču gan es , gan mani vecāki uzreiz saprata, ka tas nav tas ko mēs vēlamies, labākais variants bija Rīgas valsts 1.ģimnāzija – skola kura piesaista tādus skolniekus kā es – ar labām matemātikas zināšanām.",
            "Tā nu es sāku iet uz iestājeksāmenu kursiem Rīgas valsts 1. ģimnāzijā. Tur dotos uzdevumus pildīju, bet papildus īsti nemācījos, laikam biju pārāk augstprātīgs un domāju, ka esmu jau tāpat pietiekami gudrs. Tā nu es visiem apkārtējiem skandināju – “Es mācīšos Rīgas valsts 1. ģimnāzijā”, līdz pienāca rezultāti par iestājeksāmeniem, un godīgi sakot, tas bija viens no maniem lielākajiem dzīves satricinājumiem – iestājies es nebiju. Toreiz pārdzīvojums bija milzīgs , papildus tam vēl apkaunojums par lielo lielīšanos, ka tur mācīšos. Pārdzīvoju ilgi, bet dzīve neapstājās un tā arī devos uz Rīgas valsts 2. ģimnāzijas iestājeksāmenu, eksāmens problēmas nesagādāja, un skolā iestājos.",
            "Ar 7. klasi uzsāku gaitas Rīgas valsts 2. ģimnāzijā, uzreiz bija jūtams cits līmenis salīdzinot ar Rīgas 6. vidusskolu, arī man par laimi, mūzikas instruments vairs nebija jāspēle. Taču pēc 8. klases 1. semestra beigām notika var teikt pirmā lielā karjieras izvēlē. Jau pēdējos 2 gadus sapratu, ka futbolists es nebūšu, arī ap to laiku, kā jau pusaudzim futbols nedaudz bija apnicis , un nolēmu to pamest, paralēli tam uzsāku gaitas programmēšanas kursos, kas bija jau tā laika karjieras izvēle – programmētājs.",
        ]
    },
    ['5']: {
        title: "5. Dators – iespējas vai tomēr laika tērēšana",
        text: [
            "Dators – iespējas vai tomēr laika tērēšana uz mani ir attiecināma uz mani ļoti vienkārši, vai es datoru izmantoju lietderīgi , vai tomēr es tikai spēlēju datorspēles. Kā jau iepriekš aprakstīju ar datorspēlēm iepazinos ļoti agri – 7 gadu vecumā, līdz 10. gadiem tā arī bija vienīgā mana nodarbošanās pie datora. Nedaudz vēlāk nejauši atklāju, ka man ļoti patīk filmēt video. Tā arī pašmācības ceļā iemācījos gan filmēt video, gan tos rediģēt, “montēt”. Var teikt ka šī nodarbošanās ar video filmēšanu arī nejauši man palīdzēja saskarties ar pirmajiem programētāja darbiem, tas ir , man kā jaunietiem, kas tajā laikā bija populāri, obligāti vajadzēja savu blogu. Tā nu es sāku veidot savu pirmo mājaslapu “Wordpress” platformā, drīz vien arī sapratu, ka ar programmēšanas lietām man ļoti patīk darboties.",
            "Līdz šim brīdim, datorspēles nekur nebija pazudušas, bet es uz tām skatījos citādāk, tā bija mana reklasācija, citiem jauniešiem tajā laikā tā bija televīzora skatīšanās vai iešana ārā ar draugiem. Ar draugiem ārā es nevarēju iet, jo tajā laikā dzīvoju Ķekavā, bet mācījos Rīgā un visi mani draugi bija no Rīgas , tā nu lūk šādi es ar viņiem socializējos – spēlējot kopīgi datoru, var teikt, ka viens datoru spēlēju ļoti reti, lielākoties ar draugiem. Tomēr par programmēšanu nebiju aizmirsis un tā paralēli datorspēlēm biežāk vasarās, pašmācības ceļā mācījos programmēšanu, vienreiz pat mēģināju no “Youtube” video uztaisīt savu “Facebook”. Šie “Youtube” pamācošie video arī bija mans pamats manām programmēšanas zināšanām.",
            "Tad kad pienāca 8. klases 1. semestra beigas , nolēmu doties uz programmēšanas pulciņu, kur vēl vairāk vēlējos attīstīt savas zināšanas, bet tā līdz galam nekad nebiju pieķēries programmēšanai – bieži vien vairāk bija datorspēles nekā tiešām produktīva programmēšana, un iesāktie programmēšanas projeti parasti neilga ilgāk kā 1-1,5 mēnešus, par spīti visam tam var teikt, ka arī pateicoties datorspēlēm, biju iemācījies diezgan daudz gan par datoriem, gan par operētājsistēmu “Windows”, gan par pirmajiem programmēšanas pamatiem.",
        ]
    },
    ['6']: {
        title: "6. Jauni mērķi un jauni izaicinājumi",
        text: [
            "8.klases beigās jau sākās pirmās runas par tikšanu Rīgas valsts 1. ģimnāzijā,  tākā lēnām tuvojās 10. klase, tad atkal parādījās vēlme tur iestāties uz 10. klasi. Motivācija šoreiz bija lielāka nekā 6. klasē – tomēr gribējās pierādīt citiem, ka es varu tur iestāties, taču vēl motivāciju papildināja iespēja iestāties programmēšanas novirziena klasē. Uzreiz sapratu, ka tā ir un būs laba iespēja turpināt savu programmētāja karjieru un papildināt savas zināšanas. Un visai motivācijai pa virsu, kā benzīna muca ugunskurā, bija noruna ar tēti – ja tikšu 1. ģimnāzijā, tad tikšu pie jauna datora.",
            "Tā nu es sāku iet atkal uz Rīgas valsts 1. ģimnāzijas iestājeksāmenu kursiem, taču šoreiz, mācoties no kļūdām, papildus kursiem patstāvīgi mājās mācījos, var pa teikt dažos brīžos spiedu sevi mācīties papildus. Motivācija bija lielāka kā nekad, tāpēc zināju, ka es to varu un ka man to vajag. Negribu samelot bet noteikti izpildīju 2/3 no visu gadu 10. klases iestājeksāmeniem, lai kārtīgi sagatavotos. Līdz pienāca eksāmena diena, ieraugot eksāmenu un visus uzdevumus uznāca neliels sašutums un pārdzīvojums un nodomāju, “viss , laikam tomēr nav lemts man”, uzdevumi uz pirmo acu skatienu likās grūti, un priekš manis neizpildāmi, taču viss ko darīju ir vienkārši sāku tos rēķināt, tā arī beigās visus uzdevumus izpildīju, 2 reiz pārbaudīju un ar diezgan lielu pārliecību zināju – “šoreiz man ir jātiek”. Un tā izrādījās taisnība , eksāmenu biju nolicis veiksmīgi un biju ticis pie jauna datora, bet godīgi sakot toreiz un tagad lielāks prieks ir par tieši iestāšanos Rīgas valsts 1. ģimnāzijā.",
            "Tā nu 10. klasē uzsāku mācīties 1. ģimnāzijā, šeit uzreiz kā iepriekš bija jūtams cits līmenis salīdzinot ar 2. ģimnāziju, varbūt ne tik liels kā starp 2. ģimnāziju un 1. ģimnāziju. Uzreiz varēja arī pamanīt, ka šeit ir sanākuši gudri cilvēki, ar vienu mērķi – mācīties. Varbūt arī vēlviens iemesls tam ir tāds, ka mēs visi bijām daudz nobriedušāki nekā 5 – 9. klasē, bet atšķirības bija. 10.klases vidū atgriezos pie trenēšanās futbolā, taču šoreiz savam priekam, biju nedaudz sailgojies pēc futbola un gribējās vēl uzspēlēt un patrenēties.",
        ]
    },
    ['7']: {
        title: "7. Pēdējā finiša taisne....vai tomēr ?",
        text: [
            "Paralēli programmēšanai man arī interesēja ķīmija, jau pirms ķīmijas stundām, kuras sākās 8. klasē, man jau interesēja ķīmija, ķīmijas stundas vēl to vairāk apliecināja, atzīmes ķīmijā man bija labas un vēlme mācīties ķīmiju arī liela, piedalījos 3 ķīmijas olimpiādēs, divām no tām tiku līdz valsts kārtai, papildus tam vidusskolā vajadzēja veidot ZPD darbu, izvēlējos to veidot ķīmijas nozarē. Darbu veidoju par tēmu “Alkaloīdu iegūšana no lupīna sēklām” jeb citiem vārdiem sakot – kā maksimāli ātrāk un efektīvāk iegūt medikamentiem vajadzīgās aktīvās vielas(alkaloīdus) no augu sēklām. Ar ZPD darbu tiku līdz Rīgas kārtai, lai arī tālāk netiku, šis bija viens no daudzajiem sasniegumiem ķīmijā. Šie visi sasniegumi nedaudz sagrozīja svaru kausus attiecībā uz savu nākotnes profesiju.",
            "2020.gada martā sākās Covid-19 pandēmija Latvijā, kas arī manīja visu iedzīvotāju ikdienu. Šis laiks arī pavēra jaunas iespējas – mācībām pievērsos nedaudz mazāk, jo nu uz skolu vairs iet nebija jāiet un viss notika attālināti. Sāku nodarboties ar vairāk programmēšanu, uzsāku kārtējo projektu, kurā mēģināju uztaisīt 2D spēli, un kā arī vienmēr sastapos ar lielām problēmām un pēc mēneša atmetu visam ar roku. Šajā brīdī arī neveiksmes programmēšanā un sasniegumi ķīmijā nosvēra visu par labu citai profesijai – ķīmijai.",
            "12.klases sākums jau bija pēdējais signāls profesijas izvēlei, ne tikai starp ķīmiju un programmēšanu, bet tagad arī ekonomiku/finansēm. Visās jomās biju kaut ko pamēģinājis, darījis. Visas izvēles izpētīju un veicu savus secinājumus. Pirmā izvēle šajā brīdī bija ekonomika/finanses, taču šo izvēli ātri izslēdzu, maksa labā augstskolā bija liela un konkurence šajā jomā milzīga. Tālāk veicu secinājumus par ķīmiju, joma kurā sasniegumi netrūka. Lai arī ķīmija man ļoti patika un patīk, sapratu, ka Latvijā pieprasījums, lai arī ir liels, atalgojums bieži vien nav atbilstošs nepieciešamajām zināšanām un atalgojums arī par bakalaura līmeņa zināšanām nav pietiekams. Tad nu beigās palika programmēšana. Pēc neveiksmīgā projekta ar 2D datorspēli tikai uz brīdi visam atmetu ar roku, taču drīz vien turpināju kaut kādus mazus projektus. Zināšanas arī bija diezgan pietiekamas, papildus tam Latvijas universitāte piedāvaja mācības ar daudzām budžeta vietām, tādejādi 12. klases beigās pirms eksāmeniem biju veicis savu izvēli. Pēc 12. klases un vidusskolas izlaiduma nākamajā dienā iesniedzu visus nepieciešamos dokumentus Latvijas universitātē uz Datorsistēmu novirzienu, un tā arī beigās mans dzīves ceļš bija mani aizvedis līdz Latvijas Universitātei.",
        ]
    },
}